[supervisord]
nodaemon = true
user = root
logfile = /dev/null
logfile_maxbytes = 0
pidfile = /run/supervisord.pid

[program:php-fpm]
command = php-fpm --nodaemonize --force-stderr
priority = 10
autostart = true
autorestart = true
startretries = 3
stopsignal = QUIT
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

[program:nginx]
command = nginx -g "daemon off;"
priority = 20
autostart = true
autorestart = true
startretries = 3
stopsignal = QUIT
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
